[package]
name = "vape"
description = "ｆｕｌｌ ｗｉｄｔｈ ａｅｓｔｈｅｔｉｃｓ"
version = "0.2.0"
authors = ["Joshua Li <joshua.r.li.98@gmail.com>"]
license = "MIT"

homepage = "https://www.github.com/JoshuaRLi/vape"
repository = "https://www.github.com/JoshuaRLi/vape"
readme = "README.md"
keywords = ["aesthetic", "vaporwave", "fullwidth"]
categories = ["command-line-utilities", "text-processing"]

[badges]
travis-ci = { repository = "JoshuaRLi/vape" }

[dependencies]
getopts = "^0.2"
rand = "~0.5.0"

[[bin]]
name = "vape"
path = "src/main.rs"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
incremental = false
# default for release: opt-level = "3"
# levels s and z are nightly-only
